include "#!./gradlew -q printConveyorConfig"
include required("/stdlib/jdk/21/amazon.conf")

app {
  display-name = "Slides"
  fsname = "slides"
  rdns-name = "com.yannickpulver.slides"
  vcs-url = "https://github.com/yannickpulver/slides"

  machines = ["mac.amd64", "mac.aarch64"]

  mac {
    info-plist.LSMinimumSystemVersion = "12.0"
    entitlements-file = composeApp/default-entitlements.plist
    entitlements {
      com.apple.security.cs.disable-library-validation = true
    }
  }

  icons = "composeApp/icon-conveyor.png"

  site {
    base-url = "https://github.com/yannickpulver/slides/releases/latest/download"
  }
}

conveyor.compatibility-level = 22
