
platform :macos do
    desc "Build Macos app"
    lane :buildDmg do |options|
        gradle(task: "packageReleaseDmg")
    end

    desc "Deploy"
    lane :deploy_dmg do |options|
        setup_ci if ENV['CI']
        buildDmg
        version_number = File.read("../VERSION").strip
        notarize(
            package: "composeApp/build/compose/binaries/main-release/dmg/Slides-#{version_number}.dmg",
            bundle_id: "com.yannickpulver.slides",
            api_key_path: "fastlane/mac-api-key.json",
            print_log: "true"
        )
    end
end
