name: "Release"

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Build JVM JAR
        run: ./gradlew :composeApp:jvmJar

      - name: Build, sign, notarize and publish
        uses: hydraulic-software/conveyor/actions/build@v22.0
        with:
          command: make copied-site
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
          extra_flags: >-
            -Kapp.site.github.oauth-token=${{ secrets.GITHUB_TOKEN }}
            -Kapp.mac.notarization.team-id=${{ secrets.APPLE_TEAM_ID }}
            -Kapp.mac.notarization.apple-id=${{ secrets.APPLE_ID }}
            -Kapp.mac.notarization.app-specific-password=${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
